version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: petproject_db_prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: project_nest
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:7-alpine
    container_name: petproject_redis_prod
    restart: unless-stopped
    networks:
      - internal

  app:
    build: .
    container_name: petproject_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@db:5432/project_nest
      PORT: 3001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ARTSEARCH_API_KEY: ${ARTSEARCH_API_KEY}
      HUMORAPI_KEY: ${HUMORAPI_KEY}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      NODE_ENV: production
    ports:
      - "127.0.0.1:3001:3001"
    depends_on:
      - db
      - redis
    networks:
      - internal

networks:
  internal:

volumes:
  pgdata:
